version: 2
jobs:
  docker_build:
    machine: true
    steps:
      - checkout
      - run: |
         docker build -t hello-world:1.0 .
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker push hello-world:1.0

vultr_deploy:
    machine: true
    steps:
      - run: |
          ssh root@usatl- (edited) 

workflows:
  version: 2
  rolling_update:
    jobs:
      - docker_build
      - vultr_deploy:
          requires:
            - docker_build
          filters:
            branches:
              only:
                - master

